### ISSUE TITLE
Implement the counting feature

### ISSUE THREAD

**Issue by sampreets3** [sampreets3/treecounter-ML#3]
As of now, the program is simply displaying the frame count of the video. Need to add the tree counting feature to the program.
Basic algorithm would be :- 
- Detect the centroid for each box
- Use the centroid against a demarcating line
- If the centroid is above the demarcating line, do nothing
-  If the centroid is below the demarcating line, increment the tree counting variable

**Comment by franklinselva** [comment]
The implementation of the tree counting feature can be adapted from the collaborator @adioshun in his Gist: 

https://gist.github.com/adioshun/779738c3e28151ffbb9dc7d2b13c2c0a

If this counter is working for a single class, we should be able to multiply it for the defined multiclass counter.
